spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: eventzen_dev
      auto-index-creation: true
  security:
    jwt:
      secret: dev_secret_key_ee8e9a4a4b4b6b7c9c9d8d8e8e8f9f9
      expiration: 86400000 # 24 hours

logging:
  level:
    com.eventzen: DEBUG
    org.springframework: INFO
