spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: eventzen_dev
      auto-index-creation: true

logging:
  level:
    root: INFO
    com.eventzen: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.security: DEBUG
