spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: eventzen_test
      auto-index-creation: true
  security:
    jwt:
      secret: dGVzdF9zZWNyZXRfa2V5X2Jhc2U2NF9lbmNvZGVkX2Zvcl9ldmVudHplbl90ZXN0cw==
      expiration: 3600000 # 1 hour

logging:
  level:
    com.eventzen: DEBUG
    org.springframework: INFO
